// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebUniversity.DataLayer;

#nullable disable

namespace WebUniversity.Migrations
{
    [DbContext(typeof(StateDbContext))]
    partial class StateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebUniversity.DataLayer.Entity.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basic mathematics course",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Basic English course",
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Basic history course",
                            Name = "History of world"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Some about world",
                            Name = "The Geografy"
                        },
                        new
                        {
                            Id = 25,
                            Description = "About stars",
                            Name = "Astronomy"
                        });
                });

            modelBuilder.Entity("WebUniversity.DataLayer.Entity.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseID = 1,
                            Name = "MA-01"
                        },
                        new
                        {
                            Id = 2,
                            CourseID = 1,
                            Name = "MA-02"
                        },
                        new
                        {
                            Id = 3,
                            CourseID = 2,
                            Name = "EN-01"
                        },
                        new
                        {
                            Id = 4,
                            CourseID = 2,
                            Name = "EN-02"
                        },
                        new
                        {
                            Id = 5,
                            CourseID = 3,
                            Name = "HI-01(modified)"
                        },
                        new
                        {
                            Id = 6,
                            CourseID = 3,
                            Name = "HI-02"
                        },
                        new
                        {
                            Id = 13,
                            CourseID = 24,
                            Name = "SR-01"
                        },
                        new
                        {
                            Id = 35,
                            CourseID = 3,
                            Name = "HI-03"
                        },
                        new
                        {
                            Id = 39,
                            CourseID = 2,
                            Name = "Fi-01"
                        },
                        new
                        {
                            Id = 46,
                            CourseID = 25,
                            Name = "ZI-1"
                        },
                        new
                        {
                            Id = 54,
                            CourseID = 3,
                            Name = "HI-04"
                        },
                        new
                        {
                            Id = 56,
                            CourseID = 24,
                            Name = "SR-02"
                        },
                        new
                        {
                            Id = 58,
                            CourseID = 24,
                            Name = "HI-04"
                        },
                        new
                        {
                            Id = 59,
                            CourseID = 3,
                            Name = "HI-04"
                        });
                });

            modelBuilder.Entity("WebUniversity.DataLayer.Entity.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 63,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Jane",
                            GroupId = 1,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Bob",
                            GroupId = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Alice",
                            GroupId = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "David",
                            GroupId = 3,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Sarah",
                            GroupId = 4,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Mike",
                            GroupId = 4,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Lisa",
                            GroupId = 4,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Tom",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Mary",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Chris",
                            GroupId = 6,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Kim",
                            GroupId = 6,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Mark",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Emily",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Eric",
                            GroupId = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Grace",
                            GroupId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Alex",
                            GroupId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Olivia",
                            GroupId = 3,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Ryan",
                            GroupId = 4,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Rachel",
                            GroupId = 4,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Daniel",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Maggie",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Ben",
                            GroupId = 6,
                            LastName = "Wang"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Sophie",
                            GroupId = 6,
                            LastName = "Wang"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Peter",
                            GroupId = 1,
                            LastName = "Gonzalez"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Cindy",
                            GroupId = 1,
                            LastName = "Gonzalez"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Adam",
                            GroupId = 2,
                            LastName = "Allen"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Eva",
                            GroupId = 2,
                            LastName = "Allen"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Frankov",
                            GroupId = 3,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Amy",
                            GroupId = 3,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "John",
                            GroupId = 1,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Jane",
                            GroupId = 1,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Bob",
                            GroupId = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Alice",
                            GroupId = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "David",
                            GroupId = 3,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Sarah",
                            GroupId = 3,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Mike",
                            GroupId = 4,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Lisa",
                            GroupId = 4,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 101,
                            FirstName = "Tom",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 102,
                            FirstName = "Mary",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 103,
                            FirstName = "Chris",
                            GroupId = 6,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 104,
                            FirstName = "Kim",
                            GroupId = 6,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 105,
                            FirstName = "Mark",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 106,
                            FirstName = " Emily",
                            GroupId = 1,
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 107,
                            FirstName = "Eric",
                            GroupId = 2,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 108,
                            FirstName = "Grace",
                            GroupId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 109,
                            FirstName = "Alex",
                            GroupId = 35,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 110,
                            FirstName = "Olivia",
                            GroupId = 39,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 111,
                            FirstName = "Ryan",
                            GroupId = 4,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 112,
                            FirstName = "Rachel",
                            GroupId = 46,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 113,
                            FirstName = "Daniel",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 114,
                            FirstName = "Maggie",
                            GroupId = 5,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 115,
                            FirstName = "Ben",
                            GroupId = 6,
                            LastName = "Wang"
                        },
                        new
                        {
                            Id = 116,
                            FirstName = "Sophie",
                            GroupId = 6,
                            LastName = "Wang"
                        },
                        new
                        {
                            Id = 117,
                            FirstName = "Peter",
                            GroupId = 1,
                            LastName = "Gonzalez"
                        },
                        new
                        {
                            Id = 118,
                            FirstName = "Cindy",
                            GroupId = 1,
                            LastName = "Gonzalez"
                        },
                        new
                        {
                            Id = 119,
                            FirstName = "Adam",
                            GroupId = 2,
                            LastName = "Allen "
                        },
                        new
                        {
                            Id = 120,
                            FirstName = "Eva",
                            GroupId = 2,
                            LastName = "Allen "
                        },
                        new
                        {
                            Id = 121,
                            FirstName = "Frank",
                            GroupId = 3,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 122,
                            FirstName = "Amy",
                            GroupId = 3,
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 125,
                            FirstName = "Oleg",
                            GroupId = 4,
                            LastName = "Lozynskyi"
                        },
                        new
                        {
                            Id = 129,
                            FirstName = "Dmytro",
                            GroupId = 2,
                            LastName = "Ivasuk"
                        },
                        new
                        {
                            Id = 131,
                            FirstName = "Dmytro",
                            GroupId = 13,
                            LastName = "Savchyn"
                        },
                        new
                        {
                            Id = 136,
                            FirstName = "Oleg",
                            GroupId = 54,
                            LastName = "Vasylyshyn"
                        });
                });

            modelBuilder.Entity("WebUniversity.DataLayer.Entity.Group", b =>
                {
                    b.HasOne("WebUniversity.DataLayer.Entity.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebUniversity.DataLayer.Entity.Student", b =>
                {
                    b.HasOne("WebUniversity.DataLayer.Entity.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebUniversity.DataLayer.Entity.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("WebUniversity.DataLayer.Entity.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
